### ISSUE TITLE
`cloudflared service install` broken on macOS

### ISSUE THREAD

**Issue by adamfeldman** [cloudflare/cloudflared#327]
Doc: https://github.com/cloudflare/cloudflare-docs/blob/production/products/cloudflare-one/src/content/connections/connect-apps/run-tunnel/run-as-service.md

### Steps to reproduce
1. `sudo cloudflared service install`
2. `tail -f /Library/Logs/com.cloudflare.cloudflared.err.log /Library/Logs/com.cloudflare.cloudflared.out.log`
3. Observe repeating line in error log ```Use `cloudflared tunnel run` to start tunnel MY_TUNNEL```

### Expected result: 
Seeing the usual tunnel startup info in the logs

### A fix that worked for me
Edit `/Library/LaunchDaemons/com.cloudflare.cloudflared.plist`

Original (runs `/usr/local/bin/cloudflared`)
```
                <array>
                        <string>/usr/local/bin/cloudflared</string>
                </array>
```
Fixed (runs `/usr/local/bin/cloudflared tunnel run`)
```
                <array>
                        <string>/usr/local/bin/cloudflared</string>
                        <string>tunnel</string>
                        <string>run</string>
                </array>
```

ref: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html

**Comment by adamfeldman** [comment]
This was originally filed here: https://github.com/cloudflare/cloudflare-docs/issues/791

**Comment by adamfeldman** [comment]
I've attached all the files:
-  [config-sanitized.yml.zip](https://github.com/cloudflare/cloudflared/files/6124188/config-sanitized.yml.zip)
-  [BROKEN-com.cloudflare.cloudflared.plist.zip](https://github.com/cloudflare/cloudflared/files/6124198/BROKEN-com.cloudflare.cloudflared.plist.zip)
- [WORKING-com.cloudflare.cloudflared.plist.zip](https://github.com/cloudflare/cloudflared/files/6124200/WORKING-com.cloudflare.cloudflared.plist.zip)
- [logs.zip](https://github.com/cloudflare/cloudflared/files/6124206/logs.zip)
  - Attached logs are for the error condition, I did not attach logs for when it's working fine with my `.plist` edits



When the problem is occurring, I only get output in `/Library/Logs/com.cloudflare.cloudflared.err.log`, and no output in `/Library/Logs/com.cloudflare.cloudflared.out.log`.

This problem occurred in `cloudflared version 2021.2.5 (built 2021-02-23-1958 UTC)` as well as a preceding version.

**Comment by adamfeldman** [comment]
Additional instructions for `.plist` editing:

1. Install service `sudo cloudflared service install` (you MUST use `sudo`, as the intention here is to run `cloudflared` at boot [per the docs](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/run-as-service#run-at-boot))
2. Edit `.plist` file
3. `sudo launchctl stop com.cloudflare.cloudflared`
3. `sudo launchctl unload /Library/LaunchDaemons/com.cloudflare.cloudflared.plist`
4. `sudo launchctl load /Library/LaunchDaemons/com.cloudflare.cloudflared.plist`
5. The service should start upon `launchctl load`, but you can also `sudo launchctl start com.cloudflare.cloudflared`

To troubleshoot `launchctl`: `launchctl dumpstate > myfile.txt` then open file and search for string `cloudflared` – this is how I realized only the command `cloudflared` was executing and not `cloudflared tunnel run`.

**Comment by ekaiser-uptycs** [comment]
can confirm - we had to deploy plists manually with Ansible to get this working.

**Comment by hultqvist** [comment]
It's the same in Windows.

Installing using legacy configuration works.

Using the new ingress configuration I can start the program from ` C:\Windows\System32\config\systemprofile\.cloudflared` using arguments `tunnel run` but starting as a windows service shuts down immediately without generating log files.

I modified the windows registry `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Cloudflared\ImagePath` adding " tunnel run" at the end and now the service starts sucessfully.

**Comment by adamfeldman** [comment]
It was frustrating to be told by Cloudflare Support that the product team did not consider this something requiring action to resolve. [I also see the same intention in this PR response](https://github.com/cloudflare/cloudflared/pull/341#pullrequestreview-651660618).

I absolutely love the Argo Tunnel product, and use it in production on multiple projects. However the learning curve was extremely steep and full of trial-and-error, due to sharp edges such as this issue (#327).

> Our Argo Tunnel product team feedback: this is broken at higher level as there's no common service mode that works across all features. We picked "client" mode for windows and macOS and the "tunnel" mode for Linux. Therefore the bug is that we had to pick, it is not the choices we made.
> 
> There won't be a fix planned for this. What've you done is the workaround which you figured out already.

My last message to Cloudflare Support:

> 1. I was not aware anything was modal – will the existence of "client" and "tunnel" modes be clearly documented?
> 
> 2. Has the product team considered adding a "--mode" flag to the "cloudflared service install" command? As well as making the OS/platform differences clear in the cli help?

**Comment by mountainash** [comment]
Thanks for your help @adamfeldman - a big help on something that I'd have expected Cloudflare to catch.

Also note (for other struggling with this) that the value of the first `<string>` item might be `/opt/homebrew/bin/cloudflared` if HomeBrew was used for the installation of Cloudflared as suggested in the [official docs](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation#macos)

**Comment by mtrujilloariza** [comment]
I'm still getting the error even after editing the plist to have tunnel run. anyone have any idea why?

**Comment by mtrujilloariza** [comment]
this plist worked for me
[com.cloudflare.cloudflared.plist.zip](https://github.com/cloudflare/cloudflared/files/6989902/com.cloudflare.cloudflared.plist.zip)

**Comment by pasuder** [comment]
I did a bit more to have it working as service/daemon on macOS, with help of @adamfeldman [findings](https://github.com/cloudflare/cloudflared/issues/327#issuecomment-796844496):

```
# setup
sudo mkdir /etc/cloudflared
sudo cp ~/.cloudflared/*.json /etc/cloudflared
sudo cp ~/.cloudflared/cert.pem /etc/cloudflared
sudo cp ~/.cloudflared/config.yml /etc/cloudflared
sudo sed -i.bak 's/\/Users\/'${USER}'\/\./\/etc\//g' /etc/cloudflared/config.yml

# check
sudo ls -la /etc/cloudflared

# install
sudo cloudflared service install

# check
sudo ls -la /Library/LaunchDaemons | grep cloudflared
sudo ls -la /Library/Logs | grep cloudflared
sudo tail /Library/Logs/com.cloudflare.cloudflared.err.log

# update
sudo launchctl unload /Library/LaunchDaemons/com.cloudflare.cloudflared.plist
sudo patch -p 1 /Library/LaunchDaemons/com.cloudflare.cloudflared.plist < cloudflared.plist.patch
sudo launchctl load -w /Library/LaunchDaemons/com.cloudflare.cloudflared.plist

# check
ps aux | grep cloudflared
sudo tail /Library/Logs/com.cloudflare.cloudflared.err.log
```

`cloudflared.plist.patch`:

```
--- /Library/LaunchDaemons/com.cloudflare.cloudflared.plist     2022-02-17 10:08:01.000000000 +0100
+++ /tmp/com.cloudflare.cloudflared.plist       2022-02-17 10:11:47.000000000 +0100
@@ -7,6 +7,8 @@
                <key>ProgramArguments</key>
                <array>
                        <string>/opt/homebrew/bin/cloudflared</string>
+                       <string>tunnel</string>
+                       <string>run</string>
                </array>
                <key>RunAtLoad</key>
                <true/>
@@ -22,4 +24,4 @@
                <key>ThrottleInterval</key>
                <integer>5</integer>
        </dict>
-</plist>
\ No newline at end of file
+</plist>
```

**Comment by edgariscoding** [comment]
I can't believe none of this is documented on the official documentation, forcing users to search the web for solutions.

Even the url given when running a tunnel is broken:

```
2022-02-28T02:35:10Z INF cloudflared will not automatically update when run from the shell. 
To enable auto-updates, run cloudflared as a service: 
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/run-tunnel/run-as-service
```

**Comment by adamfeldman** [comment]
> As for this whole thread/issue, we'll have it fixed in the scope of a big new feature. Stay tuned.

Very exciting @nmldiegues! Personally and professionally, I've found it invaluable to run `cloudflared` as a root daemon on my macOS fleets. 

Makes remote support over VNC and SSH much easier! I can stay connected over VNC even during most of the macOS update process.

**Comment by nmldiegues** [comment]
I believe this is now addressed in the context of https://blog.cloudflare.com/ridiculously-easy-to-use-tunnels/
If you start managing your Tunnels in the UI / API as described there, it will run the Tunnel as a service regardless of the OS

Otherwise, you can do the following (requires a Tunnel created since March 2022):  
```
cloudflared service install $(cloudflared tunnel token <TUNNEL>)
```

**Comment by marcopelegrini** [comment]
This is broken when you don't run as sudo

**Comment by hbarve1** [comment]
> I did a bit more to have it working as service/daemon on macOS, with help of @adamfeldman [findings](https://github.com/cloudflare/cloudflared/issues/327#issuecomment-796844496):
> 
> ```
> # setup
> sudo mkdir /etc/cloudflared
> sudo cp ~/.cloudflared/*.json /etc/cloudflared
> sudo cp ~/.cloudflared/cert.pem /etc/cloudflared
> sudo cp ~/.cloudflared/config.yml /etc/cloudflared
> sudo sed -i.bak 's/\/Users\/'${USER}'\/\./\/etc\//g' /etc/cloudflared/config.yml
> 
> # check
> sudo ls -la /etc/cloudflared
> 
> # install
> sudo cloudflared service install
> 
> # check
> sudo ls -la /Library/LaunchDaemons | grep cloudflared
> sudo ls -la /Library/Logs | grep cloudflared
> sudo tail /Library/Logs/com.cloudflare.cloudflared.err.log
> 
> # update
> sudo launchctl unload /Library/LaunchDaemons/com.cloudflare.cloudflared.plist
> sudo patch -p 1 /Library/LaunchDaemons/com.cloudflare.cloudflared.plist < cloudflared.plist.patch
> sudo launchctl load -w /Library/LaunchDaemons/com.cloudflare.cloudflared.plist
> 
> # check
> ps aux | grep cloudflared
> sudo tail /Library/Logs/com.cloudflare.cloudflared.err.log
> ```
> 
> `cloudflared.plist.patch`:
> 
> ```
> --- /Library/LaunchDaemons/com.cloudflare.cloudflared.plist     2022-02-17 10:08:01.000000000 +0100
> +++ /tmp/com.cloudflare.cloudflared.plist       2022-02-17 10:11:47.000000000 +0100
> @@ -7,6 +7,8 @@
>                 <key>ProgramArguments</key>
>                 <array>
>                         <string>/opt/homebrew/bin/cloudflared</string>
> +                       <string>tunnel</string>
> +                       <string>run</string>
>                 </array>
>                 <key>RunAtLoad</key>
>                 <true/>
> @@ -22,4 +24,4 @@
>                 <key>ThrottleInterval</key>
>                 <integer>5</integer>
>         </dict>
> -</plist>
> \ No newline at end of file
> +</plist>
> ```

thank you for this, few lines of code fixed my issue on iMac

**Comment by zenyr** [comment]
cloudflared version 2023.5.1 (built 2023-05-23-1847 UTC)

note: This is still an issue when you install as a service and required 
 1. manual copy & paste of configurations (config.json, pem, {uuid}.json) from `~/.cloudflared/*` to `/etc/cloudflared/*`
 2. manual adding of "tunnel run" xml into plist with sudo. 

And my log.err was full of 
```
Use `cloudflared tunnel run` to start tunnel {UUID}
Use `cloudflared tunnel run` to start tunnel {UUID}
Use `cloudflared tunnel run` to start tunnel {UUID}
...
```

Until editing .plist manually according to [the comment above](#issuecomment-1042735393). I edited the plist using sudo vi by hand.

**Comment by olragon** [comment]
It's still broken `cloudflared version 2023.8.2 (built 2023-08-30T15:39:52Z)`

Fix by https://github.com/cloudflare/cloudflared/issues/327#issuecomment-1042735393 with slight change by using symlink instead of copy config dir.

```bash
# stop
sudo launchctl stop /Library/LaunchDaemons/com.cloudflare.cloudflared.plist
sudo launchctl unload /Library/LaunchDaemons/com.cloudflare.cloudflared.plist

# symlink config dir
sudo ln -s ~/.cloudflared /etc/cloudflared

# change plist to call `/usr/local/bin/cloudflared tunnel run`
sudo vim /Library/LaunchDaemons/com.cloudflare.cloudflared.plist
```

```xml
<array>
        <string>/usr/local/bin/cloudflared</string>
        <string>tunnel</string>
        <string>run</string>
</array>
```

```bash
sudo launchctl load -w /Library/LaunchDaemons/com.cloudflare.cloudflared.plist
sudo launchctl start /Library/LaunchDaemons/com.cloudflare.cloudflared.plist
```

**Comment by aubreypwd** [comment]
<img width="982" alt="image" src="https://github.com/cloudflare/cloudflared/assets/1753298/76ecbc7e-f121-4c1a-a695-b5002ddcea55">

[This](https://github.com/cloudflare/cloudflared/issues/327#issuecomment-1763670368) is the correct answer that fixes the issue in 2024. I have the service installed w/out `sudo`, and so you have to modify `/Users/aubreypwd/Library/LaunchAgents/com.cloudflare.cloudflared.plist` and add the extra commands to run (do _not_ add them to the first one, it won't work, add new items below). Then run:

```
launchctl unload -w /Users/aubreypwd/Library/LaunchAgents/com.cloudflare.cloudflared.plist
launchctl load -w /Users/aubreypwd/Library/LaunchAgents/com.cloudflare.cloudflared.plist
launchctl start /Users/aubreypwd/Library/LaunchAgents/com.cloudflare.cloudflared.plist
```

@nmidiegues we need to re-open this issue to get the plist updated to include these command correctly, or the documentation on https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/local-management/as-a-service/macos/ needs to be updated about this caveat.

**Comment by ProfessorManhattan** [comment]
> I believe this is now addressed in the context of https://blog.cloudflare.com/ridiculously-easy-to-use-tunnels/ If you start managing your Tunnels in the UI / API as described there, it will run the Tunnel as a service regardless of the OS
> 
> Otherwise, you can do the following (requires a Tunnel created since March 2022):
> 
> ```
> cloudflared service install $(cloudflared tunnel token <TUNNEL>)
> ```

Hey, I tried this and this does not work. The solutions above worked. This file needs to be modified:

https://github.com/cloudflare/cloudflared/blob/eb2e4349e894b2c412bcdd026c9a34fa56e3c73e/cmd/cloudflared/macos_service.go#L44

To include:

```
                <key>ProgramArguments</key>
                <array>
                        <string>/opt/homebrew/bin/cloudflared</string>
+                       <string>tunnel</string>
+                       <string>run</string>
                </array>
```

**Comment by aubreypwd** [comment]
I mean, seriously, I still think it is bonkers that we have to modify XML just to get this to work.

**Comment by adampatterson** [comment]
I wasted so much time trying to get this to work, I had it working on another computer a long time ago and may have installed my tunnel using the managed solution but man.

**Comment by balaclava-guy** [comment]
Can someone explain how this issue is closed - I just tried to create tunnel from the web gui, pasting the exact command provided by the web gui to installed cloudflare and then the tunnel and it does not start-up on rebooting my mac.

Just spent an hour trying to debug and have no idea what the correct solution is?

**Comment by staciax** [comment]
still broken `cloudflared version 2026.2.0 (built 2026-02-06T14:21:32Z)`
macOS 13.6.7

**Comment by adampatterson** [comment]
Still broken in `cloudflared version 2026.3.0 (built 2026-03-06T12:53:40Z)`

Should we open another ticket? 

This has been an issue for years.

**Comment by dfang** [comment]
Still broken in   `cloudflared version 2026.8.2 (built 2026-08-14T11:22:52Z)`

can't believe this easy-to-fix issue exists for years
