### ISSUE TITLE
It seems impossible to use cloudflared tunnels to access an internal Docker Registry

### ISSUE THREAD

**Issue by DavidZidar** [cloudflare/cloudflared#500]
For some reason the Docker client requires `Content-Length` headers but these are stripped somewhere in the cloudflared tunnel which makes the docker CLI report the following error:

```
> docker pull myregistry.domain.tld/image:tag
Error response from daemon: missing or empty Content-Length header
```

I have verified using Firefox and the `Content-Length` header is indeed missing.

In trying to work around this issue I have tried to proxy via nginx and add a `Cacne-Control: no-transform` header to no avail. I have also tried using `​proxyType: socks` but it makes little difference, but I may be misusing the feature because I don't understand it.

Is there anything else I can try?

**Comment by nmldiegues** [comment]
I've run a docker registry behind a Cloudflare Tunnel successfully.

Steps on the server/origin machine:
1.  Set up your registry as you wish (I assume it is available on origin machine at localhost:5000)
2. `cloudflared tunnel create docker-registry`
3. `cloudflared tunnel route dns docker-registry my-docker.mydomain.com`
4. `cloudflared tunnel --url http://localhost:5000 run docker-registry` --- you could use ingress rules, I'm just simplifying here

Steps on the machine accessing:
1. `docker pull my-docker.mydomain.com/myimage:version`

And it worked fine.

**Comment by DavidZidar** [comment]
@nmldiegues Interesting, that's more or less exactly what I'm trying to do yet it doesn't work because Docker is refusing to pull anything because the `Content-Length` header is missing. The same registry is working fine if a punch a hole in my firewall.

Potential differences:
* I am using HTTPS using a Cloudflare origin certificate
* The registry is not on the same machine as the tunnel
* I am tunneling more than one service so I'm using an ingress rule

```yml
ingress:
  - hostname: myregistry.domain.tld
    service: https://internal-server.domain.tld:15443
    originRequest:
      httpHostHeader: myregistry.domain.tld
      originServerName: myregistry.domain.tld
```

**Comment by nmldiegues** [comment]
Which cloudflared version are you using?

What's your full config YAML?

**Comment by DavidZidar** [comment]
@nmldiegues cloudflared version 2021.10.5 (built 2021-10-25-1945 UTC)

```yml
tunnel: [uuid]

ingress:

  - hostname: otherservice.domain.se
    service: https://server1.ad.steamcore.se
    originRequest:
      httpHostHeader: otherservice.domain.se
      originServerName: otherservice.domain.se

  - hostname: registry.domain.se
    service: https://server2.ad.steamcore.se:15443
    originRequest:
      httpHostHeader: registry.domain.se
      originServerName: registry.domain.se
      proxyType: socks # I've tried with and without this

  - service: http_status:404
```

I can't run a tunnel on the server with the registry as it's a Synology DiskStation, so what I'm trying to do is to run the tunnel on an ingress server and proxy the traffic to the Synology.

**Comment by nmldiegues** [comment]
I can't see anything obviously wrong then.

Instead, let me show you what I did. Mostly following https://docs.docker.com/registry/deploying/ and then running a tunnel for that:

On machine 1 (the server/origin):
1. docker run -d -p 5000:5000 --restart=always --name registry registry:2
2. docker pull ubuntu:16.04
3. docker tag ubuntu:16.04 localhost:5000/my-ubuntu
4. docker push localhost:5000/my-ubuntu
5. docker image remove ubuntu:16.04
6. docker image remove localhost:5000/my-ubuntu
7. cloudflared tunnel create docker-registry
8. cloudflared tunnel route dns docker-registry my-docker.mydomain.com
9. cloudflared tunnel --url http://localhost:5000 run docker-registry

On machine 2 (the client):
1. docker pull my-docker.mydomain.com/my-ubuntu


This is my minimally working setup. Could you try to reproduce this to start "from the basics"?

**Comment by DavidZidar** [comment]
@nmldiegues Thanks, I can try. But I'm not sure how that would help tunnel my existing production registry. If those steps work I suppose I can go step by step and set up a new production registry and see when it breaks? I'll give it a go tonight.

**Comment by nmldiegues** [comment]
Exactly, that was my reasoning. I usually like to start from a place that works and iterate until we hit the problem.

**Comment by DavidZidar** [comment]
@nmldiegues I just tried to get that basic setup to work but I get the exact same error as previously, `Error response from daemon: missing or empty Content-Length header` when trying to pull an image.

**Comment by DavidZidar** [comment]
Could it be the Docker client version that makes the difference? I'm running all Debian Bullseye servers and my Docker version is 20.10.10, build b485636.

**Comment by DavidZidar** [comment]
I did a `curl -I https://my-registry.domain.tld/v2/redis/manifests/6.2.5` (the manifest of the image I pushed to my test instance via localhost:5000) and here are the headers, no `Content-Length`-header in sight.

```
HTTP/2 200
date: Wed, 03 Nov 2021 21:22:55 GMT
content-type: application/vnd.docker.distribution.manifest.v1+prettyjws
docker-content-digest: sha256:333f79b0ef80da16669ac0ce3d338e514cae96e705f2b97ee39f40f8189d6889
docker-distribution-api-version: registry/2.0
etag: "sha256:333f79b0ef80da16669ac0ce3d338e514cae96e705f2b97ee39f40f8189d6889"
x-content-type-options: nosniff
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=s%2BpjIuAN9FzZ4%2FlIjawhtH%2FmH9a8Vz80xwLzGGigEs1ICjAkZamVY%2FimMFK1UhTn6QOXFs4K6rFLBQjUrEs5vq%2B%2Bt9chylrbpTOdbz2%2FfTz81ESbzcxUJgwzJ0Z6D9dUQGPas17ZTKSQYfRu"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 6a88a929cb24f162-ARN
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400
```

**Comment by DavidZidar** [comment]
I just realized `curl -I` does a HEAD request so there is no content, but I retraced my steps and tried it with `curl -v` and still get no `Content-Length` header even though I do get the manifest.

**Comment by nmldiegues** [comment]
Ok this is odd:  apparently this (`docker pull`) works when I have WARP running on my client machine (https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp).

However, when using `curl` as you said, I still don't see the `Content-Length` header (regardless of having WARP or not enabled).

Anyway this just partly explains my confusion, since I was not understanding why I could not reproduce the issue.
Now that I can, we'll look into it.

**Comment by DavidZidar** [comment]
@nmldiegues Oh that's unexpected. Thank you! I thought I was somehow doing something wrong but I couldn't find what that would be.

**Comment by xscd** [comment]
Unrelated to issue but related to content-length I also don't get content-length info (which is annoying tbh) since a few weeks not sure if its a cloudflared version thing or something Cloudflare does on their side.

**Comment by adamus1red** [comment]
I've run into the same issue. As per [this forum post](https://community.cloudflare.com/t/no-content-length-header-when-response-is-compressed/134475) I've tried adding `cache-control no-transform` to the headers and still nothing.

**Comment by nmldiegues** [comment]
This should now be working.

However, it seems that this change/fix has caused a potential regression in https://github.com/cloudflare/cloudflared/issues/509
If we rollback, we'll let you know here.

**Comment by DavidZidar** [comment]
@nmldiegues Just tried it and seems to be working now, thank you! :)
